name: Run Test
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install pip and pipenv
        run: |
          sudo apt update
          sudo apt install python3-pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pipenv install

      - name: Erase coverage
        run: coverage erase

      - name: Run coverage
        run: coverage run -p --source=. --omit=*tests/* --omit=*/setup.py --omit=.tox* -m unittest discover -s tests/
